<?xml version="1.0"?>
<package format="3">
  <name>tracked_robot_hw</name>
  <version>0.0.0</version>
  <description>Hardware interface and odometry node for tracked robot</description>

  <maintainer email="you@example.com">kalb</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Core ROS -->
  <depend>rclcpp</depend>

  <!-- Messages -->
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <!-- TF -->
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <!-- Testing -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

